image: node:latest

stages:
      - build
      - deploy

cache:
      paths:
        - node_modules/

install_dependencies:
      stage: build
      script:
        - npm install
      artifacts:
        paths:
          - node_modules/

deploy:
      stage: deploy
      script: npm start

destory_other_instances:
      stage: deploy
      script: taskkill /im node.exe

